# Stage 1 : build
FROM php:8.2-apache AS builder
WORKDIR /var/www/html
COPY . . 

# Stage 2 : runtime
FROM php:8.2-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf

RUN groupadd -g 1001 diekeuser && \
    useradd -u 1001 -g diekeuser -m diekeuser && \
    # ✅ Changement du port interne d'Apache vers 8081 pour autoriser diekeuser
    sed -i 's#Listen 80#Listen 8081#' /etc/apache2/ports.conf && \
    sed -i 's#<VirtualHost \*:80>#<VirtualHost *:8081>#' /etc/apache2/sites-available/000-default.conf

COPY --from=builder /var/www/html /var/www/html

RUN chown -R diekeuser:diekeuser /var/www/html
USER diekeuser

EXPOSE 8081